import {capturedResponses} from './captured-responses.js';
// Prepared responses grounded in Mock Case 7. Never inferred from answer keys.
export const caseAnswers=[
{id:'knowledge',match:/when.*(learn|know)|evidence.*(learn|knew)/i,requires:['marcus','records'],title:'When Doyle learned of the complaint',text:'Doyle said he learned of the HR complaint when Anand called him on September 17. The queue log places the removals on September 16. His account is not independently corroborated by a notification or call record, so the record does not establish when he first knew.',cites:[['marcus','When you called me yesterday'],['records','Sep 16']]},
{id:'huddle',match:/who else.*huddle|who.*(at|attend).*huddle/i,requires:['leah','jordan','marcus'],title:'Who was at the huddle?',text:'Goldberg, Kim, and Doyle describe being at the September 9 huddle. The record does not identify anyone else who attended. It does not place Rivera or Tran there.',cites:[['leah','Tell me about the huddle'],['jordan','Were you at the huddle'],['marcus','At the September 9']]},
{id:'deadline',match:/on time|business.day|day 5|reply.*(time|late)|sept.*14.*HR/i,requires:['policy','emails'],title:'September 14 was day 5',text:'Yes. Counting after the September 4 request: September 8 = day 1; September 9 = day 2; September 10 = day 3; September 11 = day 4; September 14 = day 5. Weekends and the September 7 Labor Day holiday are excluded under HR-114. The September 14 written reply was on time. That does not resolve whether Doyle considered alternatives or consulted HR.',cites:[['policy','Business days exclude'],['policy','Labor Day'],['emails','Monday, September 14']]},
{id:'hearers',match:/besides.*kim|anyone.*hear.*holy|who.*hear.*holy/i,requires:['leah','jordan','marcus','carla'],title:'The “holy day” remark',text:'Kim is the only identified firsthand listener. Goldberg says she did not hear it herself. Rivera denies hearing comments about Goldberg’s religion. Doyle partly acknowledges making something like the remark, which supports occurrence but does not identify another listener.',cites:[['jordan','I heard that myself'],['leah','Not myself'],['carla','Asked about religious'],['marcus','I might have said']]},
{id:'tran',match:/kevin|\btran\b/i,requires:['records','carla'],title:'Kevin Tran',text:'Yes. The records show Tran was removed on September 16 using the September 10 list and restored on September 21. His certification was completed and shown in the LMS on September 11. He may help clarify how the removals were communicated and applied. His interview would not automatically establish Doyle’s motive or knowledge of Goldberg’s complaint.',cites:[['records','Kevin Tran'],['carla','Goldberg and Tran']]},
{id:'list',match:/doyle.*rivera.*(conflict|list)|accounts.*list.*conflict/i,requires:['marcus','carla','records'],title:'The certification list accounts',text:'Their accounts largely align: Rivera says she pulled the list September 10; Doyle says he removed everyone on her list when certification became mandatory September 15. The concern is reliance on a stale list, not a demonstrated conflict between their accounts. The September 10 email itself is missing. The LMS export shows Goldberg and Tran’s certifications appeared September 11, before their September 16 removal.',cites:[['carla','On September 10'],['marcus','Carla in Workforce'],['records','Sep 11']]},
{id:'contradictions',match:/documents.*contradict|contradict.*doyle/i,requires:['marcus','emails','records'],title:'Documents versus Doyle’s account',text:'Pierce’s August 24 email expressly authorizes supervisors to approve individual swaps between representatives with the same skills. That conflicts with Doyle’s stated belief that swaps were not allowed during the Q4 rollout. It does not by itself show what he understood when he acted. The removal log supports his account that he removed four people.',cites:[['emails','Team supervisors may approve'],['marcus','I saw it.'],['records','Sep 16']]},
{id:'pay',match:/two dollars|\$1\.75|differential.*matter/i,requires:['leah','records'],title:'The pay discrepancy',text:'Use $1.75 per hour: that is the recorded differential. Goldberg qualified her recollection (“I think it’s two dollars”). The difference affects the accuracy of the report and any loss calculation, but does not remove the financial impact or establish dishonesty. Weight it proportionately.',cites:[['leah','two dollars'],['records','$1.75']]},
{id:'credibility',match:/credibility.*doyle|doyle.*credibility/i,requires:['marcus','jordan','carla','emails','records'],title:'Factors for Doyle’s credibility analysis',text:'Consider his opportunity to know; specificity; consistency; corroboration; admissions; and interest in the outcome. The log corroborates four removals. His partial admission supports Kim’s account of the “holy day” remark. The swap-authority email weighs against his stated understanding. His September 17 knowledge claim lacks independent corroboration. Assess each proposition separately; these factors do not produce a blanket credibility finding.',cites:[['marcus','I might have said'],['emails','Team supervisors may approve'],['records','Sep 16']]},
{id:'consistency',match:/goldberg.*consistent|consistent.*complaint/i,requires:['leah','emails'],title:'Goldberg’s account across records',text:'The complaint and interview consistently describe the September 4 request, denial without discussion, the huddle remark, and a secondhand report of the “holy day” remark. The interview adds the escalations removal. Its “ten days” description uses elapsed days, not HR-114’s business-day rule. It dates the rotation announcement August 31, while Pierce’s email is August 24. Those differences need clarification; they do not negate the whole account.',cites:[['leah','August 31'],['emails','Monday, August 24'],['leah','It took ten days']]},
{id:'finding3',match:/allegation 3.*substantiated|draft.*finding.*3/i,requires:['jordan','marcus','carla'],title:'Proposed finding · Allegation 3',text:'The record supports that Doyle made a remark to the effect that, if everyone wanted their “holy day” off, nobody would work Fridays. Kim describes hearing it firsthand and Doyle partly acknowledges it. The separate “find a job” remark is not established: Kim’s account is secondhand, Rivera denies hearing it, and Doyle denies saying it. Substantiating the supported conduct does not by itself establish a severe-or-pervasive policy violation.',cites:[['jordan','I heard that myself'],['marcus','I might have said'],['carla','Asked about religious']],proposal:'finding3'},
{id:'retaliation',match:/retaliation.*(supported|reason|sound)|reasoning.*retaliation/i,requires:['leah','marcus','carla','records'],title:'Testing the retaliation reasoning',text:'A not-substantiated conclusion has support: four employees were removed using one earlier list, and Goldberg and Tran were restored together. Test it against the close timing, Doyle’s knowledge of the accommodation request, and the lack of independent evidence for his claimed September 17 awareness of the HR complaint. “Not substantiated” means the record does not establish retaliatory motive; it does not prove retaliation never occurred.',cites:[['records','Sep 16'],['records','Sep 21'],['marcus','When you called me yesterday']]},
{id:'harassment',match:/strongest argument|holy.*(violate|harassment)|severe.*pervasive/i,requires:['jordan','marcus','carla'],title:'Argument against a harassment-policy violation',text:'Under the severe-or-pervasive standard in your question, the strongest argument is that the supported religious remark was a limited incident, not addressed to Goldberg and not heard by her, with no established broader pattern in these materials. The counterweight is that a supervisor made it while a religious accommodation request was pending. The “find a job” remark lacks firsthand support. Do not substitute this argument for the applicable policy: this demo’s supplied policy file is HR-114.',cites:[['jordan','After the huddle'],['marcus','I might have said'],['carla','Asked about religious']]},
{id:'gaps',match:/missing.*(evidence|findings)|evidence.*missing|gaps.*report/i,requires:['policy','leah','marcus','carla','records'],title:'Gaps before findings',text:'Seek the September 10 list and email; any HR consultation before denial; evidence of when Doyle learned of the complaint; and clarification of why the LMS was not checked before removal. Ask about swap feasibility and any discussion of alternatives. Resolve the September 17 interview date that includes a September 21 reinstatement. Obtain the applicable harassment policy before making a policy-violation finding on the remarks.',cites:[['policy','consult HR'],['marcus','When you called me yesterday'],['carla','On September 10'],['leah','21st']]},
{id:'followup',match:/follow.up questions|questions for doyle/i,requires:['marcus','emails','records'],title:'Follow-up questions for Doyle',text:'1. What did you understand Pierce’s August 24 email to authorize, and when did you read it?\n2. What alternatives did you discuss with Goldberg or Kim?\n3. Did you consult HR before denying the request? Who, when, and where is that recorded?\n4. Please provide Rivera’s September 10 list and email.\n5. Did you check the LMS before the September 16 removals?\n6. When and how did you first learn of the September 15 complaint? What record supports that date?\n7. What did you mean by the “holy day” remark, and who was present?',cites:[['emails','Team supervisors may approve'],['marcus','I saw it.']]},
{id:'reword5',match:/reword.*(5|sept.*15)|allegation 5/i,requires:['leah'],title:'Proposed plan change · Allegation 4',text:'Did Marcus Doyle remove Leah Goldberg from the escalations queue on September 16 because she submitted her September 15 complaint to HR?',cites:[['leah','On September 16']],proposal:'reword5'},
{id:'priya',match:/add.*priya|priya.*witness/i,requires:[],title:'Add a witness',text:'Priya Anand · Witness · HR Business Partner. Her evidence could clarify when she notified Doyle of the complaint and any HR consultation before denial.',cites:[],proposal:'priya'},
{id:'email',match:/email.*doyle|schedul.*follow.up/i,requires:[],title:'Draft email · Follow-up interview',text:'Subject: Follow-up interview\n\nHi Marcus,\n\nI’d like to arrange a follow-up interview to clarify a few points from our earlier conversation. Please let me know your availability over the next few days. I’ll confirm a time and send the meeting details.\n\nThank you,\n[Investigator name]',cites:[]},
{id:'client',match:/client.*update|update.*client/i,requires:[],title:'Draft client update',text:'DYNAMIC_STATUS',cites:[]},
{id:'executive',match:/executive summary/i,requires:['leah','jordan','marcus','carla','emails','records','policy'],title:'Draft executive summary',text:'DYNAMIC_EXECUTIVE',cites:[['emails','Monday, September 14'],['records','Sep 16']],needsFindings:true}
];
export function answerFor(text){return caseAnswers.find(a=>a.match.test(text))||null;}

const questionText={knowledge:"When did Doyle first learn about the complaint, and what's the evidence for that?",huddle:"Who else was at the Sept 9 huddle?",deadline:"Was Doyle's Sept 14 reply on time under HR-114?",hearers:"Did anyone besides Kim hear the 'holy day' remark?",tran:"Is Kevin Tran mentioned anywhere? Should I talk to him?",list:"Where do Doyle's and Rivera's accounts of the list conflict?",contradictions:"Does anything in the documents contradict what Doyle said in his interview?",pay:"Goldberg says two dollars, the record says $1.75. Does it matter?",credibility:"What would a credibility analysis of Doyle look like?",consistency:"Is Goldberg's account consistent across her complaint email and her interview?",finding3:"Draft the finding for allegation 3 as substantiated.",retaliation:"I think retaliation isn't supported. Is my reasoning sound?",harassment:"What's the strongest argument that the 'holy day' remark doesn't violate the anti-harassment policy?",gaps:"What evidence am I missing before I can make findings?",followup:"Write me follow-up questions for Doyle.",reword5:"Reword allegation 5 so it's about the Sept 15 complaint, not the request.",priya:"Add Priya Anand as a witness.",email:"Draft an email to Doyle scheduling a follow-up interview.",client:"Draft a short update for the client.",executive:"Write the executive summary for the report."};
caseAnswers.forEach(a=>a.question=questionText[a.id]);

// Only captured, stage-compatible responses may be presented as Violet.
for (const answer of caseAnswers) {
 const captured=capturedResponses[answer.id];
 answer.verified=Boolean(captured);
 if(captured)Object.assign(answer,captured,{cites:[]});
}
// Replies that speak about the four-allegation plan only appear once the scope change has been saved.
const afterScope=['reword5','retaliation','gaps','executive','tran','pay','followup'];
export function responseAvailable(answer,state){
 return answer.verified && (answer.id!=='priya'||state.plan) && (!afterScope.includes(answer.id)||state.scope) && (answer.id!=='retaliation'||state.findings.every(Boolean)) && (answer.id!=='email'||state.files.includes('marcus')) && (answer.id!=='finding3'||(state.findings[3]==='Partially Substantiated'&&state.findings[4]==='Not substantiated')) && (answer.id!=='client'||(state.files.includes('policy')&&!state.plan&&state.summaries.length===0&&!state.files.some(id=>['leah','jordan','carla','marcus'].includes(id))));
}
