import {capturedScope} from './captured-scope.js';
import {openSourcePanel} from './source-panel.js';
import {capturedCitations,summaryCitations} from './captured-citations.js';
import {reportCitations} from './report-citations.js';
import {findingRows,findingsView,overallIndexes} from './findings-view.js';
import {capturedReview} from './captured-review.js';
import {capturedResponses} from './captured-responses.js';
import {complaint} from './complaint.js';
import {planView,summaryView,outlineView,confidenceView,policyText,reportView,artifacts} from './artifact-views.js';
import {answerFor,caseAnswers,responseAvailable} from './case-answers.js';
import {suggestQuestions} from './question-suggestions.js';
import {materials} from './materials.js';
import {freshJourney,progress,interviewOrder} from './journey-state.js';
const names={leah:'Leah Goldberg',jordan:'Jordan Kim',carla:'Carla Rivera',marcus:'Marcus Doyle'};
const policyNames=['Religious Accommodation Policy','Anti-Harassment Policy','Anti-Retaliation Policy'];
const recommended=findingRows.map(r=>r.recommended);
export function createJourney({reply,user,chip,esc,bottom,showIntake}){
 const answered=new Set(); let confidenceReasons={};
 let returnStage=null,savedPlan=null,pendingAnswer=null,priya=false,allegation5='Was the removal connected to the accommodation request or HR complaint?',copyText='';
 let flagReplacement=null;let s=freshJourney(),active='leah',format='bullets',revision=false,accepted=false,reportOpen=false;
 const root=()=>document.querySelector('#content');
 const mutate=(event,id)=>{s=progress(s,event,id);shelf();};
 function shelf(){document.querySelector('#case-link').innerHTML=`<button class="vt-nav-item is-on" data-journey="plan">Marcus Doyle</button><div class="vt-case-sub">${s.final?'Final report':s.stage==='report'?'Report · Draft':s.plan?'Plan final · Interviews':'Intake complete'}</div><button class="vt-nav-item" data-journey="plan">Plan ${s.plan?'✓':''}</button><button class="vt-nav-item" data-journey="interviews">Interviews · ${s.summaries.length}/4</button><button class="vt-nav-item" data-journey="questions">Ask about the case</button><button class="vt-nav-item" data-journey="gather">Documents · ${s.files.length+1}</button>${s.summaries.length===4?'<button class="vt-nav-item" data-journey="analysis">Analysis</button>':''}${s.stage==='report'||s.final?'<button class="vt-nav-item" data-journey="report">Report</button>':''}`;}
 const button=(a,t)=>`<button type="button" class="vt-chip" data-journey="${a}">${t}</button>`;
 function card(title,html,side=false){root().querySelectorAll('[data-stage-actions] button').forEach(b=>b.disabled=true);const old=document.querySelector('#current-stage');if(side&&old&&!returnStage){returnStage=old;}if(!side)returnStage=null;if(old)old.remove();const e=document.createElement('section');e.className='vt-stagecard';e.id='current-stage';e.innerHTML=`<div class="vt-stagecard-head"><span class="vt-stagecard-dot" style="background:#7043bb"></span><span class="vt-eyebrow">${title}</span></div><div class="vt-ff-body">${html}</div>`;root().append(e);
 if(!side&&!/Ask about|More of the record/.test(title)){
 const qs=suggestQuestions(s,title,[...answered]);
 if(qs.length){const d=document.createElement('div');d.className='question-suggestions';d.innerHTML='<span class="demo-label">Try asking Violet</span>'+qs.map(q=>button('question:'+caseAnswers.indexOf(q),q.question||q.title)).join('');e.append(d);}}
 if(side){const label=returnStage?.querySelector('.vt-eyebrow')?.textContent||'your case';const nav=document.createElement('div');nav.className='answer-return';nav.innerHTML=button('resume-work','← Back to '+esc(label));e.append(nav);}e.scrollIntoView({block:'start'});return e;}
 function tray(ids,label){return `<div class="material-drop" data-drop="${ids.join(',')}" tabindex="0" aria-label="${label}"><b>${label}</b><span>Drop the sample file here</span></div><div class="sample-tray"><span class="demo-label">Your demo materials</span>${ids.map(id=>`<div class="material-item"><button class="sample-file" draggable="true" data-material="${id}">▤ ${materials[id].name}</button>${button('upload:'+id,'Use this file')}${button('read:'+id,'Read')}</div>`).join('')}</div>`;}
 function source(id,needle=''){if(id==='synopsis'){const d=document.querySelector('#document');d.querySelector('h2').textContent='Case synopsis · line 1';d.querySelector('pre').textContent="Leah Goldberg, a Member Services Representative II in the Contact Center, filed a complaint on September 15, 2026, alleging that her supervisor Marcus Doyle denied her request for religious accommodation to avoid Friday evening shifts for Shabbat observance, failed to consider a coworker's offered shift swap, and made comments suggesting disrespect for her religious practice.";openSourcePanel(d);return;}if(!s.files.includes(id)&&!['policy','complaint','harassment-policy','retaliation-policy'].includes(id))return;const material=id.endsWith('-policy')?policyText(id):id==='complaint'?{name:'01_Complaint_Email_Goldberg.docx',text:complaint}:materials[id];const d=document.querySelector('#document');d.querySelector('h2').textContent=material.name;const pre=d.querySelector('pre');pre.innerHTML=material.text.split('\n').map(line=>needle&&line.includes(needle)?`<mark>${esc(line)}</mark>`:esc(line)).join('\n');openSourcePanel(d);}
 function start(){answered.clear();s=freshJourney();shelf();policy();}
 function policy(){card('Policies',`<p>Before the plan: are the policies at issue in your library? If one is missing, drop it in and I'll add it.</p>${s.files.includes('policy')?'<p>✓ Religious Accommodation Policy HR-114</p>'+button('plan','Draft the investigation plan'):tray(['policy'],'Add the policy')}<p class="demo-label">HR-114 is supplied here. The existing case also uses Anti-Harassment and Anti-Retaliation policies from its library; their captured excerpts are available in the plan.</p>`);}
 function plan(){if(!s.files.includes('policy'))return policy();reply(s.plan?"Here's the plan.":"Here's the plan as drafted. Finalize it when it's right.");const e=card('Investigation plan',(savedPlan||planView({final:s.plan,scope:s.scope,priya,allegation5}))+button(s.plan?'interviews':'finalize-plan',s.plan?'Show interviews':'Finalize the plan'));e.classList.add('artifact-host');}
 function interviews(){if(!s.plan)return plan();reply("Here's where the interviews stand.");card('Interviews',`<p>${s.summaries.length} of ${priya?5:4} summaries finalized. Choose a person.</p><div class="interview-tiles">${interviewOrder.map(id=>`<button class="person-tile" data-journey="person:${id}"><b>${names[id]}</b><span>${id==='leah'?'Complainant':id==='marcus'?'Subject':'Witness'}</span><small>${s.summaries.includes(id)?'Summary finalized':s.files.includes(id)?'Record added · Summary next':s.outlines.includes(id)?'Outline ready':'Not yet interviewed'}</small></button>`).join('')}${priya?'<div class="person-tile"><b>Priya Anand</b><span>Witness · Not scheduled</span><small>No prepared interview in this demo</small></div>':''}</div>${s.summaries.length===4?button('gather','Gather remaining evidence'):''}`);}
 function person(id){active=id;card(names[id]+' · '+(id==='leah'?'Complainant':id==='marcus'?'Subject':'Witness'),`<p>${id==='carla'?'Carla’s prepared record is interview notes, not a verbatim transcript.':'Prepare the outline, then bring in the completed interview.'}</p>${button('outline:'+id,s.outlines.includes(id)?'View interview outline':'Generate interview outline')}${s.files.includes(id)?button('summary:'+id,'Read interview summary'):button('record:'+id,id==='carla'?'Add interview notes':'Upload transcript')}${button('interviews','All interviews')}`);}
 function outline(id){mutate('outline',id);card('Interview outline · '+names[id],outlineView(id)+button('record:'+id,id==='carla'?'Continue with interview notes':'Conduct the interview / add transcript')).classList.add('artifact-host');}
 function record(id){if(s.files.includes(id))return summary(id);card(names[id]+' · '+(id==='carla'?'Interview notes':'Interview & transcripts'),`<p>${id==='carla'?'Add the notes from Carla’s phone interview.':'For the demo, the interview has already been conducted. Drag in its prepared transcript.'}</p>${tray([id],id==='carla'?'Add interview notes':'Upload transcript')}`);}
 function upload(id){if(s.files.includes(id)){reply('That file is already in the case.');return;}mutate('upload',id);user('Added '+materials[id].name);if(id==='policy'){reply('The policy is added.');plan();}else if(interviewOrder.includes(id)){active=id;reply(id==='carla'?'The interview notes are added.':'The transcript is added; the interview is marked complete.');if(id==='leah'&&!s.scope){card('Interview added',`<p class="demo-label">Demo guide · The interview introduces a possible change to the investigation’s scope. Ask Violet to propose it, or review the summary first.</p>${button('propose-scope','Ask Violet to add the retaliation allegation')}${button('summary:leah','Review her summary first')}`);}else summary(id);}else gather();}
 function proposeScope(){
 user('Keep all three existing allegations and both existing policy groups unchanged. Propose adding a fourth allegation under the Anti-Retaliation Policy: whether Marcus Doyle removed Leah Goldberg from the escalations queue because she requested a religious accommodation or complained to HR. Show the proposed change for my review before saving.');
 const e=card('Violet',capturedScope.body+capturedScope.card+capturedScope.caveat);
 e.classList.add('captured-response');
 e.querySelectorAll('.av-cite').forEach((b,i)=>b.dataset.scopeSource=i);
 e.querySelectorAll('.vt-stagecard-foot button').forEach(b=>b.dataset.journey=b.textContent.includes('Save')?'scope':'keep-scope');
 }
 function summary(id){if(!s.files.includes(id))return record(id);active=id;const e=card('Interview summary · '+names[id],summaryView(id,format)+(!s.summaries.includes(id)?button('final-summary:'+id,'Finalize'):'<p>✓ Summary finalized</p>')+button('interviews','Summarize another witness')+(id==='leah'&&!s.scope?button('propose-scope','Ask Violet to add the retaliation allegation'):''));e.classList.add('artifact-host');}
 function gather(){if(!s.plan)return plan();const missing=['emails','records'].filter(id=>!s.files.includes(id));card('Documents',`<p>${s.summaries.length<4?'You can add evidence now and return to the interviews.':'That’s everyone interviewed. Drop in anything else you have: emails, messages, records, notes.'}</p>${missing.length?tray(missing,'Add case documents'):'<p>✓ Email and chat records<br>✓ Workforce and training records</p>'}<details><summary>Files in the case</summary>${s.files.map(id=>button('read:'+id,materials[id].name)).join('')}</details>${s.summaries.length<4?button('interviews','Return to interviews'):!missing.length?button('analysis','That’s everything'):''}`);}
 function ready(){return s.summaries.length===4&&['emails','records'].every(k=>s.files.includes(k));}
 function analysis(){if(!ready())return gather();card('What next',`<p>Next, the analysis: build the evidence matrix, the timeline, or go straight to the report.</p>${button('matrix:0','Build the evidence matrix')}${button('timeline','Build the timeline')}${button('findings','Straight to the report')}`);}
 const evidence=[['The request and denial','Goldberg asked on September 4. Doyle denied it September 14. HR-114 excludes weekends and Labor Day from business days. The denial fell on the fifth business day after the request.','emails','Monday, September 14'],['Authority to approve a swap','Pierce’s email expressly allowed supervisors to approve individual swaps. Doyle said he thought they were not allowed.','emails','Team supervisors may approve'],['Why four people were removed','The log records four removals, all based on the September 10 certification list. This contradicts Goldberg’s belief that she was the only one.','records','Kevin Tran']];
 function timeline(){if(!ready())return gather();reply("Here's the timeline: every dated event, and what doesn't line up.");card('Timeline · 20 events',`<p>Existing generated timeline · expand an event to read its detail.</p><ol class="actual-timeline">${artifacts.events.map(e=>`<li><time>${esc(e.date)}</time><details><summary>${esc(e.title)}</summary><p>${esc(e.description)}</p><small>${esc(e.source)}</small>${e.flags.map(f=>`<p class="timeline-flag">⚑ ${esc(typeof f==='string'?f:JSON.stringify(f))}</p>`).join('')}</details></li>`).join('')}</ol>${button('matrix:0','View evidence matrix')}${button('findings','Decide findings')}`);}
 function matrix(i){if(!ready())return gather();reply("Here's the evidence matrix: who and what supports each allegation.");const g=artifacts.groups[i];card('Evidence matrix · By allegation',`<nav class="artifact-tabs">${artifacts.groups.map((g,j)=>button('matrix:'+j,g.title)).join('')}</nav><h3>${esc(g.title)}</h3>${g.entries.map(e=>{const id=e.source.includes('Leah')?'leah':e.source.includes('Jordan')?'jordan':e.source.includes('Carla')?'carla':'marcus';return `<section class="matrix-account"><h4>${esc(e.source.replace(/(Complainant|Witness|Subject)/,' · $1'))}</h4><p>${esc(e.text)}</p><button class="vt-chip" data-cite="${id}">View source</button></section>`;}).join('')}${button('findings','Decide findings')}`);}
 function findings(){if(!ready())return gather();card('Your findings',`<p>Record a finding for each allegation, then the overall policy finding.</p>${findingsView(s.findings)}${button('confidence','Check evidence alignment')}`);}
 function confidence(){if(s.findings.some(v=>!v)){reply('Choose a finding for each question first.');return;}const differences=overallIndexes.filter(i=>s.findings[i]!==recommended[i]);card('Evidence alignment',`<h2>${differences.length?'Review recommended':'Evidence aligned'}</h2><p>Review what the evidence supports for each finding. You can keep your original findings or change them to the recommendations. Explanations are optional. Existing report text is not rewritten.</p><ul class="confidence-assessment">${confidenceView(s.findings,overallIndexes,recommended,confidenceReasons)}</ul><p class="demo-label">Full saved assessment from the fictional case.</p>${button('findings','Review all findings')}${button('report','Save and proceed')}`);}

 function report(){try{mutate('report');}catch(e){reply(e.message);return;}reportOpen=true;document.querySelector('.vt-main').classList.add('with-report');let panel=document.querySelector('#report-pane');if(!panel){panel=document.createElement('aside');panel.id='report-pane';document.querySelector('.vt-main').append(panel);}panel.innerHTML=`<div class="report-toolbar"><h2>Investigation report</h2>${button('close-report','Close report')}</div><p>Draft · Marcus Doyle</p><div>${button('flag','⚑ Review flag')}${button('citation','Review citation')}</div><article class="report-paper"></article><div class="report-footer">${button('redraft','Redraft the religious-remarks analysis')}${button('final-report','Finalize report')}<small>${s.flag?'✓ Flag addressed':'1 sample flag to review'} · ${s.citation?'✓ Citation reviewed':'1 sample citation to review'}</small></div>`;
 const paper=panel.querySelector('.report-paper');paper.innerHTML=reportView();
 const headings=[...paper.querySelectorAll('h2')].filter(h=>/^[IVX]+\. /.test(h.textContent));
 headings.forEach((h,i)=>{h.id='report-section-'+i;});
 const toc=document.createElement('details');toc.className='report-contents';toc.innerHTML='<summary>Report sections · 8</summary>'+headings.map((h,i)=>`<button class="vt-chip" data-report-section="${i}">${esc(h.textContent)}</button>`).join('');paper.before(toc);
 if(revision){const h=headings[6];h.id='revised-section';let next=h.nextElementSibling;while(next&&next!==headings[7]){const remove=next;next=next.nextElementSibling;remove.remove();}const note=document.createElement('div');note.className='revision';note.innerHTML=capturedResponses.redraft.html+(accepted?'<small>Revision kept · finding unchanged</small>':button('keep-revision','Keep')+button('undo-revision','Undo'));h.after(note);}
 if(flagReplacement!==null)paper.innerHTML=paper.innerHTML.replace((capturedReview.flaggedSentences[0]||'').replace(/[¹²³⁴⁵⁶⁷⁸⁹⁰]+$/,''),esc(flagReplacement));
 const flagSentence=(capturedReview.flaggedSentences[0]||'').replace(/[¹²³⁴⁵⁶⁷⁸⁹⁰]+$/,'');for(const p of paper.querySelectorAll('p')){if(p.textContent.includes(flagSentence)){p.innerHTML=p.innerHTML.replace(flagSentence,'<button class="flag-sentence" data-journey="flag">'+flagSentence+'</button>');break;}}
 const chosen=document.createElement('p');chosen.className='demo-label';chosen.textContent='Captured generated report · '+(overallIndexes.every(i=>s.findings[i]===recommended[i])?'Matches your policy findings.':'Your findings differ from this captured report. Its original conclusions are shown for review; they have not been regenerated.');paper.before(chosen);
 const cited=[...paper.querySelectorAll('p')].find(p=>p.textContent.includes('saw the offer'));
 if(cited){const b=document.createElement('button');b.className='vt-chip';b.dataset.journey='citation';b.textContent='Inspect citation';cited.append(b);}
 card('Report',`<p>The report is open on the right. Read it, inspect a flagged passage or citation, or ask me to revise a section.</p>${button('redraft','Explain the religious remarks more clearly')}${button('flag','Review the flag')}${button('citation','Check the citation')}`);}
 function synopsisForReport(){return 'This investigation concerns Leah Goldberg’s complaint about Marcus Doyle’s response to her religious accommodation request and remarks about religious observance.'+(s.files.includes('leah')?' It also considers her subsequent account of removal from escalations.':'');}
 function review(kind){const d=document.querySelector('#document');d.querySelector('h2').textContent=kind==='flag'?'Flag review':'Citation review';const pre=d.querySelector('pre');pre.innerHTML=kind==='flag'?`<mark>${esc((capturedReview.flaggedSentences[0]||'').replace(/[¹²³⁴⁵⁶⁷⁸⁹⁰]+$/,''))}</mark>${capturedReview.flagHtml}`:`<mark>Marcus confirmed that he saw the offer and explained, "I didn't think swaps were allowed during the Q4 rollout, so I didn't pursue it."</mark><p>${esc(reportCitations['23'].title)}</p>${reportCitations['23'].html}${button('review-citation','Mark reviewed')}`;
 if(kind==='flag'){pre.querySelectorAll('dialog').forEach(e=>e.remove());pre.querySelectorAll('button').forEach(b=>{b.dataset.journey=b.textContent.includes('Edit')?'edit-flag':b.textContent.includes('Remove')?'remove-flag':'address-flag';});}
 openSourcePanel(d);}
 function dispatch(a){try{
 if(a==='resume-work'){pendingAnswer=null;if(returnStage){document.querySelector('#current-stage')?.remove();root().append(returnStage);returnStage.scrollIntoView({block:'start'});returnStage=null;}else if(!s.plan)plan();else if(s.stage==='report')report();else if(ready())analysis();else interviews();return;}
 if(a==='questions'){card('Ask about this case',`<p>Try any of these in the message box, or choose one.</p>${caseAnswers.map((q,i)=>responseAvailable(q,s)?button('question:'+i,q.title):'').join('')}`);}if(a.startsWith('question:')){const q=caseAnswers[Number(a.split(':')[1])];user(q.question||q.title);showAnswer(q);}
 if(a==='copy-answer'){navigator.clipboard.writeText(copyText).then(()=>reply('Copied.')).catch(()=>reply('Select and copy the draft text above.'));}
 if(a==='cancel-answer'){pendingAnswer=null;dispatch('resume-work');}
 if(a==='accept-answer'&&pendingAnswer){if(pendingAnswer==='finding3'){reply('The proposed conduct finding is saved in this conversation. It does not change the separate Anti-Harassment Policy determination.');}if(pendingAnswer==='reword5'){savedPlan=null;s.flag=false;s.final=false;mutate('scope');allegation5='Did Marcus Doyle remove Leah Goldberg from the escalations queue, which carries a pay differential, on September 16, 2026, because she submitted her complaint to HR on September 15, 2026?';reply('Allegation 4 is updated.');plan();}if(pendingAnswer==='priya'){savedPlan=null;s.flag=false;s.final=false;priya=true;reply('Priya Anand is added as a witness for follow-up. No interview record for her is included in these materials.');plan();}pendingAnswer=null;}
 if(a==='plan')plan();if(a==='finalize-plan'){const p=document.querySelector('#current-stage .vt-plan');if(p){p.querySelector('.vt-eyebrow').textContent='Investigation plan · final';savedPlan=p.outerHTML;}mutate('plan');interviews();}if(a==='interviews')interviews();if(a==='gather')gather();if(a==='analysis')analysis();if(a==='timeline')timeline();if(a==='findings')findings();if(a==='confidence')confidence();if(a==='propose-scope')proposeScope();if(a==='keep-scope'){summary('leah');}if(a==='scope'){savedPlan=null;mutate('scope');reply('The retaliation allegation is added to the plan.');summary('leah');}
 const [cmd,id]=a.split(':');if(cmd==='person')person(id);if(cmd==='outline')outline(id);if(cmd==='record')record(id);if(cmd==='upload')upload(id);if(cmd==='read'){// Reading a provided sample does not add it to the case.
 const was=s.files.includes(id);if(!was)s.files.push(id);source(id);if(!was)s.files=s.files.filter(k=>k!==id);
 }if(cmd==='summary')summary(id);if(cmd==='format'){format=id;summary(active);}if(cmd==='final-summary'){mutate('summary',id);interviews();}if(cmd==='matrix')matrix(Number(id));if(cmd==='align'){mutate('finding',{index:Number(id),value:recommended[Number(id)]});confidence();}
 if(a==='report')report();if(a==='close-report'){document.querySelector('#report-pane')?.remove();document.querySelector('.vt-main').classList.remove('with-report');reportOpen=false;}if(a==='flag'||a==='citation')review(a);if(a==='address-flag'||a==='review-citation'){mutate(a==='address-flag'?'flag':'citation');document.querySelector('#document').close();report();}
 if(a==='edit-flag'){const pre=document.querySelector('#document pre');pre.innerHTML='<label>Edit this sentence<textarea id="flag-edit" rows="5">'+esc((capturedReview.flaggedSentences[0]||'').replace(/[¹²³⁴⁵⁶⁷⁸⁹⁰]+$/,''))+'</textarea></label>'+button('save-flag-edit','Save');}if(a==='save-flag-edit'){flagReplacement=document.querySelector('#flag-edit').value;dispatch('address-flag');}if(a==='remove-flag'){flagReplacement='';dispatch('address-flag');}
 if(a==='redraft'){user('Redraft the religious-remarks analysis to distinguish what occurred from whether the record shows severe or pervasive conduct. Keep my finding unchanged.');revision=true;accepted=false;report();document.querySelector('#revised-section').scrollIntoView({block:'start'});}if(a==='keep-revision'){accepted=true;report();}if(a==='undo-revision'){revision=false;accepted=false;report();}if(a==='final-report'){if(!overallIndexes.every(i=>s.findings[i]===recommended[i])){reply('This captured report has different conclusions from your findings. Review the findings or keep it as a draft; the demo cannot regenerate a full alternative report.');return;}if(revision&&!accepted){reply('Keep or undo the pending revision before finalizing.');return;}mutate('finalize');reply('The report is finalized in this demo.');document.querySelector('#report-pane')?.remove();document.querySelector('.vt-main').classList.remove('with-report');card('Investigation complete',`<p>4 interviews reviewed. Evidence gathered. Findings recorded. Report reviewed and finalized.</p><p>The report remains a local fictional demonstration. Nothing was uploaded or sent.</p>${button('read-final','Read final report')}`);}if(a==='read-final'){report();s.final=true;s.stage='complete';shelf();document.querySelector('#report-pane>p').textContent='Final · Marcus Doyle';document.querySelectorAll('#report-pane [data-journey="redraft"],#report-pane [data-journey="final-report"]').forEach(b=>b.remove());}
 }catch(e){reply(e.message);}}
 function showAnswer(answer){
 if(!responseAvailable(answer,s)){card('Demo guide',`<p>This response has not been captured from Violet for this point in the case yet.</p><p>Your work is still here. Continue where you left off.</p>`,true);return;}

 const missing=answer.requires.filter(id=>!s.files.includes(id));
 if(missing.length){card('More of the record is needed',`<p>To answer that from this case’s record, add the following prepared materials first.</p>${tray(missing,'Add the missing materials')}<p>Then ask the question again.</p>`,true);return;}
 if(answer.needsFindings&&s.findings.some(v=>!v)){reply('Record your findings first so the executive summary reflects your decisions.');findings();return;}
 if(answer.id==='priya'){priya=true;savedPlan=null;shelf();}
 if(answer.id==='executive'&&!s.findings.every((v,i)=>v===recommended[i])){card('Demo guide','<p>The captured executive summary follows the recorded findings. Review yours before using it.</p>'+button('findings','Review findings'),true);return;}
 answered.add(answer.id);
 for(const host of [root(),returnStage].filter(Boolean)){host.querySelectorAll('.question-suggestions button').forEach(b=>{const q=caseAnswers[Number(b.dataset.journey?.split(':')[1])];if(q&&answered.has(q.id))b.remove();});host.querySelectorAll('.question-suggestions').forEach(e=>{if(!e.querySelector('button'))e.remove();});}
 let text=answer.text;

 copyText=text;pendingAnswer=answer.id==='priya'?null:answer.proposal||null;
 const answerCard=card(answer.title,`<div class="answer-copy captured-response">${answer.html||esc(text)}</div><div>${answer.cites.filter(([id])=>s.files.includes(id)).map(([id,q],i)=>`<button class="vt-chip" data-cite="${id}" data-needle="${esc(q)}">Source ${i+1} · ${materials[id].name}</button>`).join('')}</div>${button('copy-answer','Copy')}${answer.id==='priya'?button('interviews','Show interviews'):''}${pendingAnswer?button('accept-answer','Save this change')+button('cancel-answer','Not now'):''}`,true);
 answerCard.classList.add('draft-response');answerCard.querySelector('.vt-stagecard-head').innerHTML='<strong>● Violet</strong>';
 const provenance=document.createElement('small');provenance.className='response-provenance';provenance.textContent=answer.captureNote.startsWith('Full captured')?'Captured from Violet · complete response':answer.captureNote.startsWith('Complete live')?'Captured from Violet · earlier-stage scenario':'Captured excerpt · '+answer.captureNote;answerCard.querySelector('.answer-return').prepend(provenance);
 }
 function route(text){if(/tell me about.*case|show.*intake|case.*overview/i.test(text)){reply(synopsisForReport());showIntake();return true;}if(/redraft|rewrite/.test(text)){dispatch('redraft');return true;}const answer=answerFor(text);if(answer){showAnswer(answer);return true;}const t=text.toLowerCase();if(/report/.test(t)&&!/redraft|rewrite/.test(t)){dispatch('report');return true;}if(/redraft|rewrite|severe|pervasive/.test(t)){dispatch('redraft');return true;}if(/plan/.test(t)){dispatch('plan');return true;}if(/timeline/.test(t)){dispatch('timeline');return true;}if(/matrix|evidence alignment/.test(t)){dispatch(t.includes('alignment')?'confidence':'matrix:0');return true;}if(/finding/.test(t)){dispatch('findings');return true;}if(/interview|summary|summarize|outline/.test(t)){const id=interviewOrder.find(k=>t.includes(k))||active;dispatch((/outline/.test(t)?'outline:':/summary|summarize/.test(t)?'summary:':'person:')+id);return true;}if(/upload|document|file/.test(t)){dispatch('gather');return true;}if(/next|attention/.test(t)){dispatch(!s.plan?'plan':s.summaries.length<4?'interviews':ready()?'analysis':'gather');return true;}return false;}
 document.addEventListener('click',e=>{const b=e.target.closest('button');if(b?.dataset.scopeSource!==undefined){const t=document.createElement('template');t.innerHTML=capturedScope.sources[b.dataset.scopeSource];const aside=t.content.querySelector('aside');aside.querySelectorAll('button').forEach(x=>x.remove());const d=document.querySelector('#document');d.querySelector('h2').textContent=aside.getAttribute('aria-label')||'Source';d.querySelector('pre').innerHTML=aside.innerHTML;openSourcePanel(d);}if(b?.dataset.reportSection){document.querySelector('#report-section-'+b.dataset.reportSection)?.scrollIntoView({block:'start'});}if(b?.dataset.realCitation){const c=artifacts.citations[b.dataset.realCitation];if(c){const d=document.querySelector('#document');d.querySelector('h2').textContent=c.title;d.querySelector('pre').innerHTML=c.lines.map(l=>l.on?'<mark>'+esc(l.text)+'</mark>':esc(l.text)).join('\n');openSourcePanel(d);}}if(b?.dataset.pick!==undefined){mutate('finding',{index:Number(b.dataset.pick),value:b.dataset.value});const opts=b.closest('.vt-fx-opts');opts.querySelectorAll('button').forEach(x=>{const on=x===b;x.classList.toggle('is-on',on);x.setAttribute('aria-checked',String(on));});}if(b?.dataset.journey)dispatch(b.dataset.journey);if(b?.dataset.cite||b?.dataset.reportCitation){const key=(b.getAttribute('title')||b.getAttribute('aria-label')||'').replace(/^Source \d+: /,'');const [person,num]=(b.dataset.summaryCitation||'').split(':');const c=b.dataset.reportCitation?reportCitations[b.dataset.reportCitation]:summaryCitations[person]?.[num]||capturedCitations[key];if(c){const d=document.querySelector('#document');d.querySelector('h2').textContent=c.title;d.querySelector('pre').innerHTML=c.html;openSourcePanel(d);}else if(b.dataset.cite)source(b.dataset.cite,b.dataset.needle);}});
 document.addEventListener('input',e=>{if(e.target.dataset.confidenceReason!==undefined)confidenceReasons[e.target.dataset.confidenceReason]=e.target.value;});
 document.addEventListener('change',e=>{if(e.target.dataset.finding!==undefined)mutate('finding',{index:Number(e.target.dataset.finding),value:e.target.value});});
 document.addEventListener('dragstart',e=>{const b=e.target.closest('[data-material]');if(b)e.dataTransfer.setData('text/violet-material',b.dataset.material);});
 document.addEventListener('dragover',e=>{const d=e.target.closest('[data-drop]');if(d){e.preventDefault();d.classList.add('is-drag');}});document.addEventListener('dragleave',e=>e.target.closest('[data-drop]')?.classList.remove('is-drag'));
 document.addEventListener('drop',e=>{const d=e.target.closest('[data-drop]');if(!d)return;e.preventDefault();d.classList.remove('is-drag');const id=e.dataTransfer.getData('text/violet-material');if(d.dataset.drop.split(',').includes(id))dispatch('upload:'+id);else reply('Drag a sample file from the tray for this step. No personal files are uploaded.');});
 return {start,route,reset(){confidenceReasons={};returnStage=null;savedPlan=null;s=freshJourney();pendingAnswer=null;priya=false;allegation5='Was the removal connected to the accommodation request or HR complaint?';revision=false;accepted=false;flagReplacement=null;format='bullets';document.querySelector('#report-pane')?.remove();document.querySelector('.vt-main').classList.remove('with-report');}};
}
