import {openSourcePanel,setupSourcePanel} from './source-panel.js';
import {createJourney,track} from './case-journey.js';
import {complaint} from './complaint.js';
const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const synopsis='Leah Goldberg made a formal complaint to HR about her supervisor, Marcus Doyle. She says he denied her request not to work Friday evenings after 5 PM for Shabbat, did not discuss a coworker’s proposed shift swap, and took ten days to respond. She also reports a remark made to her at a team huddle and a religious remark relayed to her by Jordan. She asks HR to investigate and help keep her Friday evenings free.';
let phase='home',generation=0,form,people,framework,step;
const chip=(action,text)=>`<button type="button" class="vt-chip" data-do="${action}">${text}</button>`;
function reply(text){const e=document.createElement('div');e.className='reply';e.innerHTML='<strong>● Violet</strong><div>'+esc(text)+'</div>';$('#content').append(e);}
function user(text){const e=document.createElement('div');e.className='bubble';e.textContent=text;$('#content').append(e);}
function bottom(){const e=$('.vt-home');e.scrollTop=e.scrollHeight;}
let journey;
function reset(){journey?.reset();generation++;phase='home';framework='conduct';step=0;form={title:'Marcus Doyle',synopsis,issue:'Discrimination',reported:'09/15/2026',unit:'Contact Center',country:'',notes:'Complaint submitted by Leah Goldberg to Priya Anand, HR. Jordan is mentioned as a coworker; his surname is not stated in this complaint.',priority:'',channel:'',category:'Complaint'};people=[{name:'Leah Goldberg',role:'Complainant',title:'Member Services Representative II'},{name:'Marcus Doyle',role:'Subject',title:'Supervisor'},{name:'Jordan',role:'Witness',title:'Coworker'}];$('#case-link').innerHTML='';$('#content').innerHTML=`<div class="vt-hello"><div><h1>Good evening, friend.</h1><p>Your work, across cases.</p></div></div><button class="vt-start" id="drop" aria-label="Start a case"><span class="vt-start-icon">＋</span><span><b>Start a case</b><span>Tell me what you have: files, a complaint you can describe, or just a name. I'll ask you what I need and set it up with you. Drop files here any time.</span></span><span class="vt-start-go">Start with Violet</span></button><div class="sample-tray"><span class="demo-label">Try it · fictional complaint</span><button class="sample-file" id="sample" draggable="true">▤ 01_Complaint_Email_Goldberg.docx</button><small>Drag the sample onto Start a case.</small><div>${chip('use','Use sample complaint')}${chip('show','Show me how')}${chip('read','Read complaint')}</div></div>`;const d=$('#drop');d.onclick=()=>{reply('Happy to. How would you like to begin?');choices([['use','I have files to drop in']]);bottom();};d.ondragover=e=>{e.preventDefault();d.classList.add('is-drag');};d.ondragleave=()=>d.classList.remove('is-drag');d.ondrop=e=>{e.preventDefault();d.classList.remove('is-drag');if(e.dataTransfer.getData('text/violet-sample')==='complaint')upload();else {reply('Use the fictional sample for this demo. Your own files are not read or uploaded.');bottom();}};$('#sample').ondragstart=e=>e.dataTransfer.setData('text/violet-sample','complaint');}
function choices(items){const d=document.createElement('div');d.className='demo-choice';d.innerHTML=items.map(([a,t])=>chip(a,t)).join('');$('#content').append(d);}
async function animate(){if(phase!=='home')return;const a=$('#sample').getBoundingClientRect(),b=$('#drop').getBoundingClientRect(),g=$('#sample').cloneNode(true);g.removeAttribute('id');g.classList.add('drag-ghost');Object.assign(g.style,{left:a.x+'px',top:a.y+'px',width:a.width+'px'});document.body.append(g);const version=generation;await g.animate([{transform:'translate(0,0)',opacity:1},{transform:`translate(${b.x+b.width/2-a.x-a.width/2}px,${b.y+b.height/2-a.y}px)`,opacity:.85}],{duration:matchMedia('(prefers-reduced-motion: reduce)').matches?0:1100,easing:'ease-in-out',fill:'forwards'}).finished;g.remove();if(version===generation)upload();}
function upload(){if(phase!=='home')return;phase='reading';track('sandbox_start');const version=generation;$('#content').innerHTML='';user('Here is a file for a new case: 01_Complaint_Email_Goldberg.docx');reply("Reading it now. The draft will appear below when it's ready.");const e=document.createElement('div');e.className='vt-stagecard';e.id='reading';e.innerHTML='<div class="vt-ff-body" role="status">Reading 01_Complaint_Email_Goldberg.docx…<div class="vt-progress"><span style="width:65%"></span></div></div>';$('#content').append(e);setTimeout(()=>{if(version!==generation)return;e.remove();phase='draft';draft();},900);}
function field(key,label,long=false){return `<div class="vt-ff-line"><span class="vt-ff-k">${label}</span><button class="vt-editable ${long?'vt-editable-block':''}" data-field="${key}">${esc(form[key]||'Not in the files · click to add')}</button></div>`;}
function draft(){document.querySelector('#draft')?.remove();const e=document.createElement('section');e.id='draft';e.className='vt-stagecard';e.innerHTML=`<div class="vt-stagecard-head"><span class="vt-stagecard-dot" style="background:#7043bb"></span><span class="vt-eyebrow">New case</span><span class="vt-stagecard-title">The case, drafted from 1 file</span></div><div class="vt-ff-body"><div role="status">Your draft is ready. Please review the details below, then finalize it or edit anything that needs changing.</div>${field('title','Case name')}${field('synopsis','What happened',true)}${field('issue','Issue')}${field('reported','Reported')}${field('unit','Business unit')}${field('country','Country')}${field('notes','Intake notes',true)}<div class="vt-ff-sec"><div class="vt-eyebrow">People found</div>${people.map((p,i)=>`<div class="vt-ff-person"><input class="vt-inline" aria-label="Name ${i+1}" data-person="${i}" data-key="name" value="${esc(p.name)}"><select class="vt-inline" aria-label="Role ${i+1}" data-person="${i}" data-key="role">${['Complainant','Subject','Witness'].map(r=>`<option ${r===p.role?'selected':''}>${r}</option>`).join('')}</select><input class="vt-inline" aria-label="Title ${i+1}" data-person="${i}" data-key="title" value="${esc(p.title)}"><button class="vt-icon-btn" data-remove="${i}" aria-label="Remove ${esc(p.name)}">×</button></div>`).join('')}${chip('add','＋ Add a person')}</div><div class="vt-ff-sec"><div class="vt-eyebrow">Files</div><div class="vt-ff-file"><span>01_Complaint_Email_Goldberg.docx</span><select class="vt-inline" aria-label="File type">${['Complaint','Evidence','Policy'].map(c=>`<option ${form.category===c?'selected':''}>${c}</option>`).join('')}</select></div></div><div class="vt-ff-sec"><b>Framework</b><span class="vt-quiet">Preset for an external investigation; change it if this one evaluates a policy.</span><div>${chip('policy','Policy-based: was a policy violated?')}${chip('conduct','Conduct-based: did the conduct occur?')}</div></div></div><div class="vt-stagecard-foot"><button type="button" class="vt-chip is-next" data-do="finalize">Finalize and open case</button>${chip('edit','Edit draft')}<span class="vt-stagecard-hint">Nothing is saved until you finalize.</span></div>`;$('#content').append(e);{const f=e.querySelector(`[data-do="${framework}"]`);f.classList.add('is-on');f.setAttribute('aria-pressed','true');}e.scrollIntoView({block:'start'});}
function ask(){const questions=[['channel','Where was it first raised?',['HR','Security','Hotline','Tell Violet','Other','Skip for now']],['priority','How urgent is it?',['Critical','High','Medium','Low']],['country','Which country?',['United States','Canada','Skip for now']]].filter(([k])=>!form[k]);if(!questions.length){phase='intake';intake();return;}phase='questions';const [key,text,options]=questions[0];step=key;reply(text);choices(options.map(x=>['answer:'+x,x]));bottom();}
function intake(){reply("Here's the intake. Click anything to change it.");const e=document.createElement('section');e.className='vt-stagecard';e.innerHTML=`<div class="vt-stagecard-head"><span class="vt-stagecard-dot" style="background:#7043bb"></span><span class="vt-eyebrow">Intake</span><span class="vt-stagecard-title">${esc(form.title)}</span></div><div class="vt-ff-body">${field('issue','Issue')}${field('priority','Priority')}${field('reported','Received')}${field('channel','Came in through')}${field('unit','Business unit')}${field('country','Country')}<div class="vt-ff-line"><span class="vt-ff-k">People</span><span>${people.map(p=>esc(p.name)+' · '+esc(p.role)).join('<br>')}</span></div>${field('synopsis','What happened',true)}</div><div class="vt-stagecard-foot"><button type="button" class="vt-chip is-next" data-do="looks">Looks right</button><span class="vt-stagecard-hint">Click anything to change it; it saves as you go.</span></div>`;$('#content').append(e);e.scrollIntoView({block:'start'});}
function action(a){if(a==='read'){$('#complaint').textContent=complaint;openSourcePanel($('#document'));}if(a==='use')upload();if(a==='show')animate();if(a==='add'){people.push({name:'',role:'Witness',title:''});draft();}if(['policy','conduct'].includes(a)){framework=a;draft();}if(a==='edit')$('#draft [data-field="title"]').click();if(a==='finalize'&&phase==='draft'){phase='questions';$('#content').innerHTML=`<h1>${esc(form.title)}</h1>`;$('#case-link').innerHTML=`<button class="vt-nav-item is-on" data-do="overview">${esc(form.title)}</button>`;ask();}if(a.startsWith('answer:')&&phase==='questions'){const v=a.slice(7);form[step]=v==='Skip for now'?'Not set':v;user(v);$('.demo-choice:last-child')?.remove();ask();}if(a==='overview'){reply('Leah Goldberg has raised concerns about the handling of her religious accommodation request and remarks about religious observance. The complaint is the source so far.');if(phase==='home')upload();else intake();}if(a==='looks'){phase='journey';reply('Good. The intake is set.');journey.start(framework);}}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.do)action(b.dataset.do);if(b.dataset.remove){people.splice(Number(b.dataset.remove),1);draft();}if(b.dataset.field){const k=b.dataset.field,v=document.createElement(['synopsis','notes'].includes(k)?'textarea':'input');v.className='vt-inline';v.value=form[k];v.setAttribute('aria-label',k);b.replaceWith(v);v.focus();v.onblur=()=>{form[k]=v.value;b.textContent=v.value||'Not in the files · click to add';v.replaceWith(b);};v.onkeydown=e=>{if(e.key==='Enter'&&v.tagName==='INPUT')v.blur();};}});
document.addEventListener('change',e=>{if(e.target.dataset.person!==undefined)people[Number(e.target.dataset.person)][e.target.dataset.key]=e.target.value;});
$('#chat').onsubmit=e=>{e.preventDefault();const t=$('#message').value.trim();if(!t)return;$('#message').value='';user(t);if(phase==='questions'){action('answer:'+t);return;}if(phase==='journey'){if(!journey.route(t)){reply('Try a question about the record, the plan, interviews, findings, or report.');bottom();}return;}if(/start|upload|attach|files|complaint/i.test(t)&&phase==='home'){upload();return;}if(/marcus|intake|synopsis|about.*case/i.test(t)){action('overview');return;}if(/looks right/i.test(t)&&phase==='intake'){action('looks');return;}reply(phase==='draft'?'Review the draft below, then use “Finalize and open case.”':'This preview follows the sample complaint through intake. Use the sample file to begin.');bottom();};$('#reset').onclick=reset;$('#home').onclick=reset;$('#attach').onclick=()=>{if(phase==='home')upload();else {reply('The sample complaint is already here.');bottom();}};$('#close').onclick=()=>$('#document').close();setupSourcePanel($('#document'));journey=createJourney({reply,user,esc});reset();
