export const intents={inbox:'Review incoming inbox reports',start:'Start a new case',overview:'Ask for an overview of a case without naming one',marcus:'Tell me about Marcus case: overview, background, status, or select his case; not his interview summary',plan:'Draft or review investigation plan',interviews:'Who to interview or conduct interviews',outline:'Draft or review interview questions or outline',next:'What comes next in the current case',confirm:'Yes or confirm the currently pending proposal',cancel:'Cancel the pending proposal',resume:'Return to the interrupted Marcus case',home:'Home priorities: what needs my attention, where should I start, what can you do, show my cases',summary:'Show or summarize Marcus Doyle interview',narrative:'Switch interview summary to narrative paragraphs',bullets:'Switch interview summary to quick bullets',source:'Show evidence or transcript source for a statement',report:'Open or draft the full investigation report',redraft:'Revise harassment analysis to explain severe or pervasive threshold, keep finding unchanged',shorten:'Shorten current harassment analysis',keep:'Keep or accept the pending report revision',undo:'Undo or reject the report revision',flag:'Inspect a report review flag',citation:'Inspect a report citation',maya:'Review Maya Lindgren case plan status',note:'Add reminder to review Maya draft plan',support:'Locate missing upload or diagnose upload problem',unknown:'Unsupported request or unclear intent'};
export function localRoute(text,view='home'){
 const early=openingRoute(text);if(early)return early;const t=text.toLowerCase();if(/^(yes|yes please|confirm|go ahead|do it)[.! ]*$/.test(t))return 'confirm';if(/^(cancel|not now|no thanks)[.! ]*$/.test(t))return 'cancel';if(/back to|resume/.test(t))return 'resume';if(/what.*next|next step/.test(t))return 'next';if(/outline|interview questions/.test(t))return 'outline';if(/who.*interview|conduct.*interview/.test(t))return 'interviews';if(/plan/.test(t)&&!/maya|note|remind/.test(t))return 'plan';if(/^(marcus|marcus doyle)[.! ]*$/.test(t))return 'marcus';if(/\b(undo|revert|reject)\b/.test(t))return 'undo';if(/\b(keep|accept|approve)\b/.test(t))return 'keep';if(/\b(shorter|shorten|concise|tighten)\b/.test(t))return view==='report'?'shorten':'unknown';if(/narrative/.test(t))return 'narrative';if(/bullet/.test(t))return 'bullets';if(/flag/.test(t))return 'flag';if(/citation/.test(t))return 'citation';if(/(where.*(say|said)|source|transcript|back.*up)/.test(t))return 'source';if(/upload|missing.*file/.test(t))return 'support';if(/maya/.test(t)&&/note|remind/.test(t))return 'note';if(/maya/.test(t))return 'maya';if(/(redraft|rewrite|revis|emphasis|focus|severe|pervasive|why.*harass)/.test(t))return 'redraft';if(/report/.test(t))return 'report';if(/interview|summari|summary|marcus/.test(t))return 'summary';if(/attention|inbox|home|across|what.*next/.test(t))return 'home';return 'unknown';
}

// High-confidence opening requests do not need a paid classifier.
export function openingRoute(text){
 const t=text.toLowerCase().trim().replace(/[’']/g,'').replace(/[?!.,]/g,'');
 if(/\b(outline|transcript|interview|report|citation|source|draft|rewrite|redraft|note|remind|upload)\b/.test(t))return null;
 if(/\bmarcus\b/.test(t)&&/\b(case|about|overview|background|status|stands|going|happened)\b/.test(t))return 'marcus';
 if(/\bmaya\b/.test(t))return 'maya';
 if(/^(hi|hello|hey)( violet)?$/.test(t)||/\b(what needs my attention|what should i (do|work on)|where (do|should) i (start|begin)|what can (you|i) do|help me (start|get started)|show me (my )?cases|across (my |the )?cases|whats (on my plate|pending)|catch me up)\b/.test(t))return 'home';
 if(/^(show |review |open |check )?(my |the )?inbox$/.test(t))return 'inbox';
 if(/^(start|create|open|set up) (a )?(new )?case$/.test(t))return 'start';
 if(/^(tell me about|show me|review|summarize|what is the status of) (the |this |my )?case$/.test(t))return 'overview';
 return null;
}
