import {freshFlow,transition} from './flow.js';
import {localRoute,openingRoute} from './intents.js';
const $=s=>document.querySelector(s), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={view:'home',format:'bullets',revision:null,kept:false,note:false,flag:false,citation:false,sound:false,busy:false};
const suggestions={home:['What needs my attention?','Draft Marcus’s investigation plan','Review Maya’s plan'],summary:['Show the source','Use narrative format','Open the report'],report:['Focus on why it wasn’t severe or pervasive','Review a flag','Check a citation'],maya:['Remind me to review Maya’s plan','Summarize Marcus’s interview'],support:['Open the report','What needs my attention?']};
const excerpts=[['Doyle said he declined Goldberg’s Friday evening request because he did not believe he could change the regional Q4 rotation.',1],['He acknowledged seeing Jordan Kim’s shift-swap offer but did not pursue it.',2],['He partly acknowledged the Friday and “holy day” remarks, but said they were not aimed at Goldberg.',3],['He said he removed Goldberg from escalations because of a certification list, and learned about her HR complaint on September 17.',5]];
const revised='The supported remarks and the policy finding are separate questions. Doyle partly acknowledged the Friday and “holy day” remarks, and Kim described hearing the latter firsthand. This supports that remarks occurred. The record does not establish a broader pattern or sufficient severity to meet the severe-or-pervasive standard applied in this fictional analysis. The reported “find a job” remark lacks firsthand support and cannot be treated as established. The finding remains Not Substantiated; this does not mean the supported remarks were appropriate. The accommodation-policy finding remains separate.';
const short='The record supports that some remarks occurred, but does not establish sufficient severity or a pervasive pattern under the policy standard applied here. The “find a job” remark lacks firsthand support. The finding remains Not Substantiated; that is not a finding that the supported remarks were appropriate.';
function say(text,audio){const m=document.createElement('div');m.className='message violet';m.innerHTML='<span class="speaker">● Violet</span><p>'+esc(text)+'</p>';$('#messages').append(m);m.scrollIntoView({block:'nearest'});if(state.sound&&audio){$('#voice').src='/demo/audio/'+audio+'.mp3';$('#voice').play().catch(()=>{$('#hint').textContent='Audio could not play. The complete response is shown above.';});}}
function choices(){ $('#suggestions').innerHTML=(suggestions[state.view]||suggestions.home).map(t=>`<button data-prompt="${esc(t)}">${esc(t)}</button>`).join('');}
function home(){state.view='home';$('#artifact').hidden=true;$('.workspace').classList.remove('has-artifact');$('#page-title').textContent='Home';$('#page-subtitle').textContent='Your work, across cases.';choices();}
function artifact(title,html){$('#artifact').hidden=false;$('.workspace').classList.add('has-artifact');$('#page-title').textContent=state.view==='maya'?'Maya Lindgren':'Marcus Doyle';$('#page-subtitle').textContent='Fictional case · Your choices stay in this session';$('#artifact').innerHTML=`<div class="artifact-top"><div><h2>${title}</h2><small>${state.view==='maya'?'Plan awaiting review':'INV-2026-0096 · Marcus Doyle'}</small></div></div>${html}`;$('#artifact').scrollTop=0;choices();}
function summary(){state.view='summary';const items=excerpts.map(([text,id])=>`${esc(text)} <sup><button data-source="${id}" aria-label="Read citation ${id}">${id}</button></sup>`);artifact('Interview summary',`<div class="tabs" role="group" aria-label="Summary format"><button data-action="bullets" aria-pressed="${state.format==='bullets'}">Quick bullets</button><button data-action="narrative" aria-pressed="${state.format==='narrative'}">Narrative</button></div><div class="paper"><p class="eyebrow">SELECTED EXCERPTS · MARCUS DOYLE</p><h2>Bottom line</h2><p>Doyle described following the regional rotation and denied targeting Goldberg because of her religion.</p><h2>His account</h2>${state.format==='bullets'?'<ul>'+items.map(t=>'<li>'+t+'</li>').join('')+'</ul>':items.map(t=>'<p>'+t+'</p>').join('')}<p class="eyebrow">Click a citation to read the transcript.</p></div>`);}
function report(){state.view='report';const template=document.createElement('template');template.innerHTML=window.VIOLET_EXPANDED.report;template.content.querySelectorAll('h2').forEach(h=>{if(h.textContent.startsWith('VII.')){h.id='harassment';if(state.revision){let n=h.nextElementSibling;while(n&&n.tagName!=='H2'){let next=n.nextElementSibling;n.remove();n=next;}const d=document.createElement('div');d.className='revision'+(state.kept?' kept':'');d.innerHTML=`<small>${state.kept?'REVISION KEPT':'PREPARED REVISION · FINDING UNCHANGED'}</small><p>${esc(state.revision)}</p>${state.kept?'':`<button class="primary" data-action="keep">Keep</button><button data-action="undo">Undo</button>`}`;h.after(d);}}});artifact('Investigation report',`<div class="review-tools"><button data-action="flag">⚑ Flag review${state.flag?' ✓':''}</button><button data-action="citation">⁑ Citation review${state.citation?' ✓':''}</button></div><div class="paper"><p class="eyebrow">FULL DRAFT · 8 SECTIONS</p>${template.innerHTML}</div>`);const paper=$('.paper');paper.querySelectorAll('p').forEach(p=>{if(p.textContent.includes('September 17')&&p.textContent.includes('Priya')&&!paper.querySelector('.flag')){p.innerHTML+=` <button class="flag" data-action="flag">⚑ Review attribution</button>`;}});}
function modal(title,html){$('#source-title').textContent=title;$('#source-content').innerHTML=html;if(!$('#source').open)$('#source').showModal();}
function source(id=2){const c=window.VIOLET_REFINED.citations[id];const hits=c.lines.filter(l=>l.on&&l.n>0).map(l=>l.n);const low=Math.min(...hits)-6,high=Math.max(...hits)+4;modal('Marcus Doyle · Source transcript',`<p class="eyebrow">CITATION ${id} · HIGHLIGHTED SOURCE PASSAGE</p>`+c.lines.filter(l=>l.text.trim()&&l.n>=low&&l.n<=high).map(l=>`<div class="source-line ${l.on?'hit':''}"><span>${l.n}</span><p>${esc(l.text)}</p></div>`).join(''));}
function legacyAct(action){
 if(action==='home'){home();say('The inbox has reports waiting, and Maya’s draft plan needs review. Marcus’s interview summary and report are ready to explore.');}
 else if(['summary','narrative','bullets'].includes(action)){if(action!=='summary')state.format=action;summary();say(action==='summary'?"The summary card for Marcus Doyle’s interview is up.":`Here’s the ${state.format==='narrative'?'narrative':'quick-bullet'} version. You can inspect the same sources in either view.`,action==='summary'?'violet-interview':null);}
 else if(action==='report'){report();say('The full report is open on the right. Ask me to revise the harassment analysis, or inspect a flag or citation.');}
 else if(action==='redraft'||action==='shorten'){state.revision=action==='shorten'?short:revised;state.kept=false;report();$('#harassment').scrollIntoView({block:'start',behavior:'smooth'});say('I’ve revised the harassment analysis to distinguish the conduct supported by the record from whether it meets the policy threshold. The finding is unchanged. Review the highlighted section; you can keep it or undo it.','violet-redraft');}
 else if(action==='keep'||action==='undo'){if(!state.revision){say('There isn’t a pending revision yet. Ask me to revise the harassment analysis first.');return;}state.kept=action==='keep';if(action==='undo')state.revision=null;report();$('#harassment').scrollIntoView({block:'start'});say(action==='keep'?'The revision is kept in your demo report. Your finding is unchanged.':'The original section is restored.');}
 else if(action==='source'){source();say('Here’s Doyle’s account of the shift-swap offer, with the supporting passage highlighted.');}
 else if(action==='citation'){modal('Citation review',`<p class="eyebrow">REPORT STATEMENT</p><p><mark>Doyle confirmed that he saw the shift-swap offer and did not pursue it.</mark></p><h3>INT-1 · Lines 43–47</h3><p>Priya Anand: Did you consider a shift swap? Jordan Kim offered one in the team chat.</p><p><mark>Marcus Doyle: I saw it. I didn't think swaps were allowed during the Q4 rollout, so I didn't pursue it.</mark></p><button data-review="citation">Mark reviewed</button>`);}
 else if(action==='flag'){modal('Flag review',`<p class="eyebrow">ATTRIBUTION · ANTI-RETALIATION</p><p><mark>He also said he first learned of the complaint when Priya Anand called him on September 17.</mark></p><h3>Keep the conclusion within the evidence.</h3><p>This is Doyle’s account. The record does not independently establish when he learned of the complaint. “Not substantiated” does not prove retaliation did not occur.</p><button data-review="flag">Mark addressed</button>`);}
 else if(action==='maya'||action==='note'){state.view='maya';artifact('Maya’s case',`<div class="card"><h3>Investigation plan</h3><p>Drafted · Awaiting investigator review</p><p>This prototype uses Maya’s case to demonstrate working across cases.</p></div>${action==='note'?`<div class="card"><h3>Save a note to Maya’s case</h3><p>I need to review the draft plan.</p><button data-save-note class="primary">Save note</button></div>`:state.note?'<div class="card">✓ Note saved: I need to review the draft plan.</div>':''}`);say(action==='note'?'I’ve prepared a reminder for Maya’s case. Review it before saving.':'Maya’s draft plan is awaiting your review.');}
 else if(action==='support'){state.view='support';artifact('Upload diagnosis',`<div class="card"><h3>Jordan Kim · witness statement.pdf</h3><p>The sample PDF is password-protected, so its text could not be read. It has not been added to the evidence.</p><button data-ticket>Show support handoff</button></div>`);say('I found the upload, but couldn’t read its contents. Here’s what went wrong.');}
 else {say('I don’t have a prepared response for that yet. Would you like to look at Marcus’s case, review Maya’s plan, or see what needs attention?');$('#suggestions').innerHTML=btn('marcus','Tell me about Marcus’s case')+btn('maya','Review Maya’s plan')+btn('home','What needs my attention?');}
}
let flow=freshFlow();
const btn=(action,label)=>`<button data-action="${action}">${label}</button>`;
function inline(title,body){
 $('.welcome')?.remove();const rail=$('[data-action="marcus"] small');if(rail)rail.textContent=flow.summary?'Interview · Summary ready':flow.transcript?'Interview · Transcript ready':flow.plan==='final'?'Plan final · Interviews':flow.plan==='draft'?'Plan · Draft awaiting review':'Intake · Ready for a plan';
 $('#artifact').hidden=true;$('.workspace').classList.remove('has-artifact');
 $('#page-title').textContent=flow.case==='marcus'?'Marcus Doyle':flow.case==='maya'?'Maya Lindgren':'Home';
 $('#page-subtitle').textContent=flow.case==='marcus'?'INV-2026-0096 · Fictional guided scenario':'Your work, across cases.';
 // Retain previous cards as a readable record, but retire their controls.
 $('#messages').querySelectorAll('.flow-card button:not([data-source])').forEach(b=>b.disabled=true);
 const card=document.createElement('section');card.className='flow-card';card.innerHTML=`<div class="flow-head"><span>●</span> ${title}</div><div class="flow-body">${body}</div>`;$('#messages').append(card);card.scrollIntoView({block:'start',behavior:'smooth'});
 $('#suggestions').innerHTML=['What next?','Review Maya’s plan','Back to Marcus'].map(t=>`<button data-prompt="${t}">${t}</button>`).join('');
}
function act(action){
 const handled=['home','inbox','start','overview','marcus','maya','plan','interviews','outline','person','sample_transcript','summary','next','confirm','cancel','note','resume','finalize_plan'];
 if(!handled.includes(action)){legacyAct(action);return;}
 const result=transition(flow,action);flow=result.state;
 const proposal=(title,description)=>inline(title,`<p>${description}</p><div class="flow-actions">${btn('confirm',title)}${btn('cancel','Not now')}</div><small>Nothing changes until you confirm. Demo only.</small>`);
 switch(result.screen){
 case 'home':home();inline('Across your cases',`<p>Two places to start: Marcus’s intake is ready for an investigation plan, and Maya’s draft plan is waiting for your review.</p><div class="early-choices">${btn('marcus','Tell me about Marcus’s case')}${btn('maya','Review Maya’s plan')}${btn('inbox','Review the inbox')}</div>`);break;
 case 'inbox':inline('Inbox · Demo preview',`<p>The full inbox is not included in this prepared scenario. You can follow Marcus’s complaint from intake or pick up Maya’s draft plan.</p>${btn('marcus','Open Marcus’s intake overview')}${btn('maya','Review Maya’s plan')}`);break;
 case 'start':inline('Start a case',`<p>In Violet, you can start with files, a complaint, or a name. Here, we’ll use the fictional complaint already prepared for Marcus’s case.</p>${btn('marcus','Read the prepared complaint')}`);break;
 case 'choose_case':inline('Which case?',`<p>Which case should I use?</p>${btn('marcus','Marcus Doyle · INV-2026-0096')}${btn('maya','Maya Lindgren · Draft plan')}`);break;
 case 'context':inline('At a glance',`<p>Leah Goldberg asked her supervisor, Marcus Doyle, for Friday evenings off to observe Shabbat. She alleges that he denied the request without considering alternatives, made remarks about religious observance, and later removed her from the escalations queue.</p><p>The investigation will examine the accommodation request, the alleged remarks, and whether the removal was retaliatory. These are allegations to investigate, not conclusions.</p><p>The complaint and policies are already available in this fictional scenario.</p><p>${flow.plan==='none'?'Next: the investigation plan.':flow.plan==='draft'?'The plan is drafted. Review it before finalizing.':'The plan is final. Next, the interviews.'}</p>${btn(flow.plan==='final'?'interviews':'plan',flow.plan==='none'?'Draft the investigation plan':flow.plan==='draft'?'Review the plan':'Show interviews')}`);break;
 case 'propose_plan':proposal('Draft the investigation plan','Use the complaint, the people identified, and the policies already in the case.');break;
 case 'plan':inline(`Investigation plan · ${flow.plan}`,`<p>4 allegations · 3 policies</p><h3>Religious Accommodation Policy</h3><ol><li>Did Doyle respond within the required time?</li><li>Did he consider alternatives and consult HR before denying the request?</li></ol><h3>Anti-Harassment Policy</h3><p>Did Doyle’s remarks violate the policy?</p><h3>Anti-Retaliation Policy</h3><p>Was Goldberg removed from escalations because of protected activity?</p><details><summary>People and documents</summary><p>Leah Goldberg · Complainant<br>Jordan Kim and Carla Rivera · Witnesses<br>Marcus Doyle · Subject</p><ul><li>Goldberg’s request and Doyle’s reply</li><li>Kim’s shift-swap offer</li><li>Religious Accommodation Policy HR-114</li></ul></details>${flow.plan==='draft'?btn('finalize_plan','Finalize the plan'):btn('interviews','Show interviews')}<small>Condensed from the fictional case. Text editing is not included in this slice.</small>`);break;
 case 'interviews':inline('Interviews',`<p>Start with the complainant, then witnesses, then the subject. You can choose a different order.</p><p>Leah Goldberg · Complainant<br>Jordan Kim · Witness<br>Carla Rivera · Witness</p>${btn('person','Marcus Doyle · Subject')}<small>This slice follows Marcus’s interview. The other interviews are part of the prepared later record.</small>`);break;
 case 'choose_person':inline('Whose outline?',`<p>This prepared branch follows Marcus Doyle.</p>${btn('person','Marcus Doyle · Subject')}`);break;
 case 'person':inline('Marcus Doyle · Subject',`<p>Usually I’d hear from the complainant and witnesses first. For this demo, we can continue with Marcus.</p>${btn('outline','Draft interview outline')}${btn('sample_transcript','Use prepared interview transcript')}`);break;
 case 'propose_outline':proposal('Draft interview outline','Questions for Marcus Doyle, covering the accommodation request, remarks, and removal from escalations.');break;
 case 'outline':inline('Interview outline · Marcus Doyle',`<h3>Accommodation request</h3><p>What did you do when Goldberg asked not to work Friday evenings?</p><p>What authority did you understand you had to approve a shift swap?</p><h3>Religious remarks</h3><p>What did you say about Fridays and “holy days”? What did you mean?</p><h3>Escalations</h3><p>How did you decide whom to remove? When did you learn of her complaint?</p>${btn('sample_transcript','Continue with prepared transcript')}<small>Condensed illustrative outline. No live interview is recorded.</small>`);break;
 case 'need_transcript':inline('Interview transcript needed',`<p>There isn’t a transcript in this scenario yet. Use Marcus’s prepared interview to continue.</p>${btn('sample_transcript','Use prepared interview transcript')}`);break;
 case 'transcript':inline('Marcus Doyle · Interview complete',`<p>The prepared transcript is now part of this demo’s record.</p>${btn('summary','Summarize the interview')}${btn('source','Read a transcript passage')}`);break;
 case 'propose_summary':proposal('Summarize the interview','Draft the summary from Marcus’s transcript and check its citations.');break;
 case 'summary':summary();{const html=$('#artifact').innerHTML;inline('Interview summary · Marcus Doyle',html);}break;
 case 'maya':inline('Maya Lindgren · Investigation plan',`<p>Drafted, not finalized. Awaiting your review.</p>${btn('note','Save a reminder to review the plan')}${btn('resume','Back to Marcus')}`);break;
 case 'note':proposal('Save note','Maya’s case: I need to review the draft plan.');break;
 case 'note_saved':inline('Note saved · Maya Lindgren',`<p>I need to review the draft plan.</p>${btn('resume','Back to Marcus')}`);break;
 case 'analysis':inline('What next',`<p>The interview summary is ready. Explore the prepared later report, including the other interviews and evidence.</p>${btn('report','Open prepared report')}<small>Jump ahead in the fictional scenario.</small>`);break;
 default:say(result.text||'Tell me what you would like to work on.');
 }
}
async function send(text,prepared=false){if(!text.trim()||state.busy)return;state.busy=true;$('#chat button').disabled=true;$('#voice').pause();const user=document.createElement('div');user.className='message user';user.textContent=text;$('#messages').append(user);$('#request').value='';user.scrollIntoView({block:'nearest'});const pending=document.createElement('div');pending.className='pending';pending.textContent='Violet is working';$('#messages').append(pending);let action=localRoute(text,state.view);try{if(prepared||openingRoute(text)){ $('#connection').textContent='Prepared case responses · No AI call needed';throw new Error('prepared choice');}const r=await fetch('/api/demo-route',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text,view:state.view,context:{case:flow.case,pending:flow.pending,plan:flow.plan,transcript:flow.transcript,summary:flow.summary}}),signal:AbortSignal.timeout(9000)});if(r.ok){const result=await r.json();action=result.action==='unknown'&&action!=='unknown'?action:result.action;$('#connection').textContent=result.mode==='jev'?'Jev understands requests · Prepared case responses':'Prepared responses · Local request matching';}}catch{}pending.remove();if(/(?:and|then|also).*\b(?:draft|summarize|review|add|file|open|remind)\b/i.test(text)){say('This slice handles one request at a time. Start with the plan, interview summary, or Maya’s note; the full multi-request sequence is still being mapped.');state.busy=false;$('#chat button').disabled=false;return;}if(/marcus/i.test(text)&&!flow.case)flow.case='marcus';act(action);state.busy=false;$('#chat button').disabled=false;$('#request').focus({preventScroll:true});}
$('#chat').onsubmit=e=>{e.preventDefault();send($('#request').value);};$('#request').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send(e.target.value);}};
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.prompt)send(b.dataset.prompt,true);else if(b.dataset.action){$('#voice').pause();act(b.dataset.action);}else if(b.dataset.source)source(b.dataset.source);else if(b.dataset.review){state[b.dataset.review]=true;$('#source').close();if(state.view==='report')report();say('Marked as reviewed in this demo.');}else if(b.hasAttribute('data-save-note')){state.note=true;b.parentElement.innerHTML='<h3>✓ Note saved to Maya’s case</h3><p>I need to review the draft plan.</p>';say('The note is saved to Maya’s demo case.');}else if(b.hasAttribute('data-ticket')){b.parentElement.innerHTML='<h3>Support ticket prepared · Demo</h3><p>The upload reached Violet, but the PDF is locked. The diagnostic details are included.</p><p class="status">Simulated handoff — no ticket is sent.</p>';say('This example shows how Violet passes the problem and its context to support.');}});
$('#close').onclick=()=>$('#source').close();$('#sound').onclick=()=>{state.sound=!state.sound;$('#sound').textContent=state.sound?'♪ Sound on':'♪ Sound off';$('#sound').setAttribute('aria-pressed',state.sound);if(!state.sound)$('#voice').pause();$('#hint').textContent=state.sound?'Recorded voice plays for the interview summary and report revision.':'Try your own words, or choose a suggestion.';};
function reset(){flow=freshFlow();Object.assign(state,{view:'home',format:'bullets',revision:null,kept:false,note:false,flag:false,citation:false});$('#voice').pause();$('#messages').innerHTML=`<div class="welcome"><p class="eyebrow">A LITTLE LESS ADMIN. A LITTLE MORE INVESTIGATING.</p><h2>Good evening, friend.</h2><p>Your work, across cases.</p><p class="eyebrow">GUIDED SCENARIO · START AT THE PLAN, EXPLORE THE LATER RECORD ANY TIME</p><div class="start-card"><h3>Start a case</h3><p>Tell me what you have: files, a complaint you can describe, or just a name. I’ll ask you what I need and set it up with you.</p><button data-action="start">Explore a prepared case →</button></div><div class="today"><div><span>Inbox</span>Reports are waiting for your review</div><div><span>Plan</span>Maya’s plan is ready for review</div><div><span>Intake</span>Marcus’s intake and policies are ready for a plan</div></div><p class="welcome-foot">For this demo, explore the two prepared cases below.</p></div>`;home();}$('#reset').onclick=reset;reset();
