// Sample answers for questions visitors commonly type that have no captured Violet reply.
// WRITTEN FOR THE DEMO in Violet's style (Oct 2026), not captured from Violet: each is labelled as such on screen.
// Every factual sentence is drawn from the supplied fictional files, and each citation opens the line it relies on.
// Order matters: the first match wins. `requires` lists the sample files that must be in the case first.
const cite=(n,id,needle,label)=>`<button type="button" class="source-number" data-cite="${id}" data-needle="${needle.replace(/"/g,'&quot;')}" aria-label="Source ${n}: ${label}" title="Source ${n}: ${label}">${n}</button>`;
const P='08_Religious_Accommodation_Policy.pdf',A='06_Exhibit_A_Emails_and_Chat.pdf',B='07_Exhibit_B_WFM_and_Training.pdf',J='03_Interview_Jordan_Kim.docx',C='05_Interview_Notes_Carla_Rivera.docx';
export const typedAnswers=[
 {id:'policy-terms',requires:['policy'],match:/(what does|what's in|what is in|summari[sz]e|explain).*(polic|hr-?114)|hr-?114.*(say|require|allow)|polic\w*.*(say|require|allow)|accommodation polic/i,
  html:`<p>HR-114 asks four things of a supervisor who gets a request:</p><ul><li>Respond in writing within five business days. Business days exclude weekends and company holidays, and Labor Day, Monday, September 7, is a 2026 holiday. ${cite(1,'policy','2. A supervisor',P)} ${cite(2,'policy','5. Company holidays',P)}</li><li>Before denying, consider reasonable alternatives, including voluntary shift swaps, schedule changes and transfers, and discuss them with the employee. ${cite(3,'policy','3. Before denying',P)}</li><li>Consult HR before denying a request he believes can't be granted. ${cite(4,'policy','4. A supervisor who believes',P)}</li><li>Don't retaliate against anyone for requesting an accommodation or raising a concern. ${cite(5,'policy','6. No employee',P)}</li></ul><p>The underlying standard is undue hardship: the policy accommodates sincerely held beliefs and practices unless the accommodation would cause undue hardship. ${cite(6,'policy','1. Harlow',P)}</p>`},
 {id:'swap',requires:['jordan'],match:/(jordan|kim).*(swap|shift|offer)|swap.*(jordan|kim|offer)|who offered|shift swap/i,
  html:`<p>Kim says he offered to take Leah's Friday evenings if she took his Saturday mornings, posted it in the team chat on September 10 and tagged Marcus. ${cite(1,'jordan','I posted it in the team chat',J)} He says Marcus reacted with a thumbs up but never said yes or no, and nobody followed up with him. ${cite(2,'jordan','He reacted with a thumbs up',J)}</p>`,
  extra:{requires:['emails'],html:`<p>Exhibit A has the chat: Kim's offer at 9:02 AM on September 10 and Marcus's thumbs-up reaction at 9:15 AM. ${cite(3,'emails','I can take Leah',A)} ${cite(4,'emails','reacted: thumbs up',A)} The regional manager's August 24 email had already said team supervisors may approve individual swaps between reps with the same skills. ${cite(5,'emails','Team supervisors may approve',A)}</p>`}},
 {id:'removed-others',requires:['records'],match:/(only one|only person|singled out|just (her|leah)|anyone else|others?|other reps).*(escalation|removed|taken off|queue)|(escalation|removed|taken off|queue).*(only one|anyone else|others|other reps|singled out)/i,
  html:`<p>No. The change log shows Marcus removed four reps from escalations on September 16, between 7:05 and 7:07 AM: Goldberg, Ngozi Okafor, Kevin Tran and Amy Bell, each recorded as "Cert not on file (LMS pull 9/10)". ${cite(1,'records','Leah Goldberg|Removed',B)} Goldberg and Tran were restored on September 21 after the list was re-pulled. ${cite(2,'records','Restored to escalations',B)}</p><p>The LMS export shows Goldberg finished the course on August 28, but it only appeared in the LMS on September 11, after the September 10 pull. ${cite(3,'records','Leah Goldberg|Aug 28',B)} So the record doesn't support her belief that she was the only one removed. It doesn't say on its own why Marcus acted on a six-day-old list.</p>`},
 {id:'carla-remark',requires:['carla'],match:/(carla|rivera).*(religio|holy|remark|comment|said|say|tell|told)|(religio|holy|remark).*(carla|rivera)/i,
  html:`<p>By her account, no. Carla's interview notes say she didn't hear Marcus say anything about Leah's religion, that she told Jordan Kim Marcus had been "grumbling about the Friday requests," and nothing more, and that she never heard him say Leah should find another job. ${cite(1,'carla','Asked about religious comments',C)}</p><p>Kim remembers it differently: he says Carla told him Marcus said something like Leah should find a job that fits her religion, and that he didn't hear it himself. ${cite(2,'jordan','Carla told me he said',J)} So that remark rests on a second-hand account that the supposed source denies, and Carla's account comes from notes, not a transcript.</p>`},
 {id:'decide',requires:[],match:/\b(did|was|is)\b.*\b(discriminat\w*|harass\w*|retaliat\w*|guilty|liable|violat\w*)|\bwho (is|was) right\b|what (are|were) the findings/i,
  html:`<p>That's your call, and I'll keep it that way: I don't decide findings. What I can do is set out what the record shows on each allegation and what cuts each way.</p><p>When the interviews and documents are in, record a finding for each allegation and I'll show you where the evidence lines up with it and where it doesn't. You can also ask me what's still missing before you decide.</p>`},
 {id:'discipline',requires:[],match:/\b(fire|fired|firing|terminat\w*|disciplin\w*|punish\w*|write (him|her) up|consequences?|sanction)\b/i,
  html:`<p>I don't recommend discipline. That decision belongs to the employer, once the findings are made. I can help you write findings that are clear about what was and wasn't established, which is what whoever makes that decision needs.</p>`},
];
// Questions about the product or the demo, answered by the demo guide rather than as Violet.
export const guideAnswers=[
 {match:/\b(price|pricing|cost|how much|trial|subscribe|plan(s)? and pricing)\b/i,text:'Pricing and the free trial are explained on the page, just below this demo.'},
 {match:/\b(secure|security|privacy|confidential|data|encrypt\w*|soc ?2|retention)\b/i,text:'This demo uses a fictional case and sends nothing anywhere. How Violet protects real case data is covered in the FAQ below the demo.'},
 {match:/\b(own files|my files|my case|upload my|real case|my documents)\b/i,text:'Not in this demo: it only uses the fictional sample files, and nothing is uploaded. With a Violet account you work with your own files.'},
 {match:/\b(how long|how fast|how quickly|speed)\b/i,text:'This demo replays answers instantly from a saved case. In Violet, drafts take a little longer because they are written from your records.'},
 {match:/\b(who are you|what are you|what is violet|what can you do|how does (this|violet) work)\b/i,text:'Violet drafts each step of a workplace investigation (plan, interview outlines, summaries and the report) from the records you give it, with sources beside every claim. You review and decide. This demo walks a fictional case through those steps.'},
];
export function typedAnswerFor(text,files){return typedAnswers.find(a=>a.match.test(text)&&a.requires.every(id=>files.includes(id)))||null;}
export function typedAnswerNeeds(text){return typedAnswers.find(a=>a.match.test(text))||null;}
export function guideAnswerFor(text){return guideAnswers.find(a=>a.match.test(text))||null;}
