"""Regenerate every citation map in compact form (Oct 7 2026). Each source text is stored once in
sandbox/source-corpora.js; citations reference it by key and line range; sandbox/source-docks.js renders the dock.
Inputs are the saved records and offline renders in ../violet-landing-backups (see README.txt)."""
import json, re, hashlib
from pathlib import Path
B = Path(__file__).resolve().parents[2] / 'violet-landing-backups'; S = Path(__file__).resolve().parents[1] / 'sandbox'
label = lambda s: re.sub(r'\s*\[[0-9a-f]{8,16}\]\s*$', '', s or '', flags=re.I).strip()
corpora = {}
def ckey(sid, src):
    k = hashlib.sha1((src['label'] + '\n' + '\n'.join(src['lines'])).encode()).hexdigest()[:10]
    corpora.setdefault(k, {'id': sid, 'label': label(src['label']), 'lines': src['lines']}); return k
def cite(sid, src, s0, e0=None, q=''):
    return {'c': ckey(sid, src), 's': s0, 'e': e0 or s0, **({'q': q} if q else {})}
# Ask Violet answers (all saved replies across the three cases), keyed by the label shown on the citation button.
answers = {}
def take(blocks):
    for b in blocks or []:
        a = b.get('answer') or {}
        for c in a.get('citations', []):
            src = (a.get('sourceCorpus') or {}).get(c['sourceId'])
            if not src: continue
            s0, e0 = c['lineStart'], c.get('lineEnd') or c['lineStart']
            key = label(src['label']) + (f", lines {s0}–{e0}" if e0 > s0 else f", line {s0}")
            answers[key] = cite(c['sourceId'], src, s0, e0)
for f in ['0096-before-recapture.json', '0105.json']:
    for m in json.loads((B / 'db-dumps' / f).read_text())['threads'][0]['messages']:
        try: take(json.loads(m['meta']).get('blocks'))
        except Exception: pass
for f in ['rendered-answers.json', 'rendered-answers-0105.json']:
    for a in json.loads((B / f).read_text()): take(a['blocks'])
summ = {}
for person, forms in json.loads((B / 'summary-cites.json').read_text()).items():
    summ[person] = {}
    for fmt, x in forms.items():
        for i, c in enumerate(x['citations']):
            src = x['corpus'].get(c['sourceId'])
            if src: summ[person][f'{fmt}-{i + 1}'] = cite(c['sourceId'], src, c['lineStart'], c.get('lineEnd'), c.get('quote') or '')
def report(rr, cp):
    R = json.loads((B / rr).read_text()); C = json.loads((B / cp).read_text())
    return {str(i + 1): cite(c['sourceId'], C[c['sourceId']], c['lineStart'], c.get('lineEnd'), c.get('quote') or '') for i, c in enumerate(R['citations']) if c['sourceId'] in C}
rep = report('rendered-report.json', 'report-corpus.json'); repc = report('rendered-report-conduct.json', 'report-corpus-conduct.json')
J = lambda o: json.dumps(o, ensure_ascii=False, separators=(',', ':'))
hdr = '// Generated by recovery-tools/build-citations-compact.py from saved INV-2026-0096/0105/0076 records.\n'
(S / 'source-corpora.js').write_text(hdr + 'export const corpora=' + J(corpora) + ';\n')
(S / 'captured-citations.js').write_text(hdr + "import {makeDocks} from './source-docks.js';\nexport const capturedCitations=makeDocks(" + J(answers) + ');\nexport const summaryCitations=Object.fromEntries(Object.entries(' + J(summ) + ').map(([k,v])=>[k,makeDocks(v)]));\n')
(S / 'report-citations.js').write_text(hdr + "import {makeDocks} from './source-docks.js';\n// Footnote n of filed report 756439ba (policy path) and of 5f137301 / INV-2026-0076 (conduct path).\nexport const reportCitations=makeDocks(" + J(rep) + ');\nexport const conductReportCitations=makeDocks(' + J(repc) + ');\n')
cp = S / 'conduct-path.js'; t = cp.read_text(); o = json.loads(t.split('export const conductPath=', 1)[1].rstrip().rstrip(';')); o.pop('reportCitations', None)
cp.write_text(t.split('export const conductPath=', 1)[0] + 'export const conductPath=' + J(o) + ';\n')
print('corpora', len(corpora), '| answer cites', len(answers), '| summary', sum(len(v) for v in summ.values()), '| report', len(rep), '| conduct report', len(repc))
