"""sandbox/conduct-scope.js: the conduct path's scope moment, INV-2026-0107 (Oct 7 2026, 16:18–16:21 UTC).
Leah's transcript filed; investigator asked "Does Leah's interview raise anything outside the current investigation plan?";
Violet answered (first answer block, rendered with the app's CitedAnswer) and proposed a plan change (VioletAction 328996de,
card rebuilt as the app's PlanChangeCard); saved; her reply. Not shown (product glitches, noted in the audit): a duplicate
second answer block in the same reply, and the line "I added a retaliation allegation... Check the policy heading on the
card" sent before anything was saved, on a conduct plan with no policy headings."""
import json, re, html, importlib.util
from pathlib import Path
B = Path(__file__).resolve().parents[2] / 'violet-landing-backups'; S = Path(__file__).resolve().parents[1] / 'sandbox'
spec = importlib.util.spec_from_file_location('bpm_helpers', Path(__file__).with_name('build-path-modules.py'))
src = Path(__file__).with_name('build-path-modules.py').read_text()
ns = {'__file__': str(Path(__file__).with_name('build-path-modules.py'))}; exec(src.split('# Policy path:')[0], ns)  # E, label, dock, inner, KEYS, answer_html
E, answer_html = ns['E'], ns['answer_html']
A = json.loads((B / 'rendered-answers-0107.json').read_text())[0]
review, _ = answer_html(A)
d = json.loads((B / 'db-dumps' / '0107.json').read_text())
act = next(a for a in d['threads'][0]['actions'] if a['id'].startswith('328996de'))
p = json.loads(act['payload']); new = json.loads(p['planData']); base = json.loads(d['case']['previousPlanData'] or '{}')  # basePlan is only a fingerprint
base_q = {q['text'] for g in (base.get('allegations') or []) for q in g['scopeQuestions']}
added = [(g.get('policyName') or 'General', q['text']) for g in new['allegations'] for q in g['scopeQuestions'] if q['text'] not in base_q]
group, qtext = added[0]
card = ('<div class="vt-stagecard"><div class="vt-stagecard-head"><span class="vt-stagecard-dot" style="background: rgb(112, 67, 187);"></span>'
        '<span class="vt-eyebrow" style="color: rgb(92, 53, 158);">Plan · proposed change</span><span class="vt-stagecard-title">Change allegations</span></div>'
        f'<div class="vt-plan vt-plan-change"><div class="vt-plan-change-group"><div class="vt-plan-group">{E(group)}</div>'
        f'<div class="vt-plan-row is-changed"><span class="vt-plan-text">{E(qtext)}<span class="vt-tag">Changed</span></span></div></div></div>'
        '<div class="vt-stagecard-foot"><button type="button" class="vt-chip is-next">Save this change</button><button type="button" class="vt-chip">Keep the plan as is</button></div></div>')
plan = json.loads((B / 'rendered-plans-0107-final.json').read_text())['0107']
(S / 'conduct-scope.js').write_text('// Generated by recovery-tools/build-conduct-scope.py (INV-2026-0107). See that script for provenance.\nexport const conductScope=' + json.dumps({
  'question': A['question'].replace('’', "'"), 'html': review, 'card': card, 'newAllegation': qtext,
  'savedReply': 'Added allegation 5. The plan was already final, so this is a change to the final plan.', 'expandedPlan': plan}, ensure_ascii=False) + ';\n')
print('added:', group, '|', qtext[:120])
