"""sandbox/section-revision.js: the real in-place rewrite of report section VII (INV-2026-0096, Oct 7 2026 16:09 UTC).

With the report open, the investigator typed the request below; Violet rewrote the section in place
(guided-report-sections artifact 3548533f), replied with the two lines below, and left the note below under the section
(captured from the page: it isn't stored with the section). "What's new" = sentences absent from the previous version
(0096-before-recapture.json). Citations are the section's own sentence citations, docked from the report's sources.
"""
import json, re, hashlib, html
from pathlib import Path
B = Path(__file__).resolve().parents[2] / 'violet-landing-backups'; S = Path(__file__).resolve().parents[1] / 'sandbox'
E = lambda s: html.escape(s, quote=False)
sec = lambda f: [x for x in json.loads([a for a in json.loads((B / 'db-dumps' / f).read_text())['artifacts'] if a['type'] == 'guided-report-sections'][-1]['content'])['sections'] if 'Anti-Harassment' in x['title']][0]
new, old = sec('0096.json'), sec('0096-before-recapture.json')
corpus = json.loads((B / 'report-corpus.json').read_text())
label = lambda s: re.sub(r'\s*\[[0-9a-f]{8,16}\]\s*$', '', s or '', flags=re.I).strip()
by_label = {label(v['label']): (k, v) for k, v in corpus.items()}
def ckey(src): return hashlib.sha1((src['label'] + '\n' + '\n'.join(src['lines'])).encode()).hexdigest()[:10]
norm = lambda s: re.sub(r'\s+', ' ', re.sub(r'[*_#>"“”]', '', s)).strip().lower()
old_text = norm(old['body'])
cites, n = {}, 0
sent_cite = {}
for c in new.get('citations') or []:
    refs = []
    for r in c['refs']:
        hit = by_label.get(label(r['label']))
        if hit: refs.append({'c': ckey(hit[1]), 's': r['lineStart'], 'e': r.get('lineEnd') or r['lineStart']})
    if refs:
        n += 1; cites[str(n)] = refs[0]; sent_cite[c['sentence']] = n
H = {'##': None, '###': 'class="text-lg font-semibold mt-6 mb-2.5 text-foreground leading-snug"', '####': 'class="text-base font-semibold mt-5 mb-2 text-foreground leading-snug"'}
out = []
for block in re.split(r'\n{2,}', new['body'].strip()):
    m = re.match(r'^(#{2,4}) (.*)$', block)
    if m:
        if m.group(1) == '##': continue  # the section heading is the report's own
        tag = 'h3' if m.group(1) == '###' else 'h4'; out.append(f'<{tag} {H[m.group(1)]}>{E(m.group(2))}</{tag}>'); continue
    para = E(block)
    for sentence, k in sorted(sent_cite.items(), key=lambda x: -len(x[0])):
        es = E(sentence)
        if es in para:
            isnew = norm(sentence) not in old_text
            para = para.replace(es, (f'<span class="rev-new">{es}</span>' if isnew else es) + f'<sup class="cite-sup-wrap"><button type="button" class="cite-sup" data-revision-citation="{k}" data-keep aria-label="View citation {k}">{k}</button></sup>', 1)
    # sentences without a citation that are still new
    for s in re.split(r'(?<=[.?!])\s+', block):
        es = E(s.strip())
        if es and norm(s) not in old_text and es in para and f'<span class="rev-new">{es}' not in para: para = para.replace(es, f'<span class="rev-new">{es}</span>', 1)
    out.append(f'<p class="mb-4 leading-[1.75] text-foreground/90">{para}</p>')
data = {
 'prompt': 'Rewrite section VII to separate what happened from whether the record shows severe or pervasive conduct. Keep my findings unchanged.',
 'replies': ['Rewriting “VII. Findings: Anti-Harassment Policy”. Violet\'s version will show in that section, to use or not.', 'Redrafted “VII. Findings: Anti-Harassment Policy”. What\'s new is highlighted; Undo is on the section.'],
 'note': "I split Section VII into two parts. 'What the Record Shows' sets out, remark by remark, what happened and how the accounts were weighed. 'Application of the Policy' then asks whether the established conduct is severe or pervasive, or affected the terms and conditions of employment. The determinations are unchanged: two remarks established and one not, which is partially substantiated on the component question, and not substantiated on the policy overall. I moved two kinds of material out of the 'holy day' sub-section and into the policy analysis: the point that the remark could reasonably be heard as referring to Leah's pending request, and the 'single remark, not addressed to her, not heard by her' weighing. Should the strongest-contrary-evidence paragraph stay as it is, or would you like it shorter?",
 'html': '\n'.join(out), 'citations': cites, 'quotesVerified': 21,
 'source': 'INV-2026-0096 · in-place section rewrite with the report open · Oct 7 2026'}
(S / 'section-revision.js').write_text("// Generated by recovery-tools/build-section-revision.py. Real in-place rewrite of report section VII; see that script.\nimport {makeDocks} from './source-docks.js';\nconst d=" + json.dumps(data, ensure_ascii=False) + ";\nexport const sectionRevision={...d,docks:makeDocks(d.citations)};\n")
print('paragraph blocks', len(out), '| citations placed', sum(o.count('data-revision-citation') for o in out), 'of', n, '| new spans', sum(o.count('rev-new') for o in out))
